// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdDOmkV_1EdUYqC5Oaf3al6xu9-smQ_E',
    appId: '1:256727257212:web:acfa7de3ffdc4f62a6f9f9',
    messagingSenderId: '256727257212',
    projectId: 'uasmobile-b93fa',
    authDomain: 'uasmobile-b93fa.firebaseapp.com',
    storageBucket: 'uasmobile-b93fa.firebasestorage.app',
    measurementId: 'G-MVK1J3TGDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9H3jQm-Mb5ZcKoajTjc90ylrUCkXqmC8',
    appId: '1:256727257212:android:4bc9cb381a457e9da6f9f9',
    messagingSenderId: '256727257212',
    projectId: 'uasmobile-b93fa',
    storageBucket: 'uasmobile-b93fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT-MFqMx5P050Pv0PdSovbSKsWcU8yKUo',
    appId: '1:256727257212:ios:1f629bf1d47d222ca6f9f9',
    messagingSenderId: '256727257212',
    projectId: 'uasmobile-b93fa',
    storageBucket: 'uasmobile-b93fa.firebasestorage.app',
    iosBundleId: 'com.example.uasmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT-MFqMx5P050Pv0PdSovbSKsWcU8yKUo',
    appId: '1:256727257212:ios:1f629bf1d47d222ca6f9f9',
    messagingSenderId: '256727257212',
    projectId: 'uasmobile-b93fa',
    storageBucket: 'uasmobile-b93fa.firebasestorage.app',
    iosBundleId: 'com.example.uasmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWdDOmkV_1EdUYqC5Oaf3al6xu9-smQ_E',
    appId: '1:256727257212:web:26e18a7b793b2b8ca6f9f9',
    messagingSenderId: '256727257212',
    projectId: 'uasmobile-b93fa',
    authDomain: 'uasmobile-b93fa.firebaseapp.com',
    storageBucket: 'uasmobile-b93fa.firebasestorage.app',
    measurementId: 'G-5P1GCFV2LG',
  );
}
